# Generated by Django 6.0.4 on 2026-05-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('corporate_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=100)),
                ('contact_no', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('enquiry_for', models.CharField(choices=[('Compliance Risk Audit', 'Compliance Risk Audit'), ('Establishment Compliances', 'Establishment Compliances'), ('Payroll Compliance Services', 'Payroll Compliance Services'), ('Factory Compliance Services', 'Factory Compliance Services'), ('Other', 'Other')], max_length=50)),
                ('heard_about', models.CharField(blank=True, choices=[('Google', 'Google Search'), ('LinkedIn', 'LinkedIn'), ('Referral', 'Referral'), ('Social Media', 'Social Media'), ('Event', 'Event/Conference'), ('Other', 'Other')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'business_enquiry',
            },
        ),
        migrations.CreateModel(
            name='ComplianceLaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=255)),
                ('official_link', models.URLField(max_length=500)),
                ('pdf_link', models.URLField(max_length=500)),
                ('key_details', models.TextField()),
            ],
            options={
                'db_table': 'compliancelaw',
            },
        ),
    ]
