# Generated by Django 6.0.4 on 2026-05-25 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_description', models.TextField()),
                ('mission_text', models.TextField()),
                ('vision_text', models.TextField()),
            ],
            options={
                'db_table': 'aboutpage',
            },
        ),
        migrations.CreateModel(
            name='DomainCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon_class', models.CharField(max_length=100)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'domaincard',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(max_length=500)),
                ('hero_subtitle', models.TextField()),
                ('banner_image_url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'homepage',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'service',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon_class', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'servicecard',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('hero_title', models.CharField(max_length=500)),
                ('hero_description', models.TextField()),
                ('cta_button_text', models.CharField(default='Request Audit', max_length=100)),
            ],
            options={
                'db_table': 'servicepage',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('icon_class', models.CharField(default='fa-solid fa-user', max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'teammember',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCardList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_items', to='Portfolio.servicecard')),
            ],
            options={
                'db_table': 'servicecardlist',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='Portfolio.service')),
            ],
            options={
                'db_table': 'servicefeature',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='servicecard',
            name='service_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='Portfolio.servicepage'),
        ),
    ]
